#!/gpfs/data/yarmarkovichlab/Frank/immunopeptidome_project/engine/SNV/snv_env/bin/python3.7

import pandas as pd
import numpy as np
import sys,os
from tqdm import tqdm
import mygene
import subprocess
import re
import argparse
import pickle
import pysam
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import bisect
from Bio.SeqIO.FastaIO import SimpleFastaParser
from Bio.Seq import Seq
from collections import Counter
import anndata as ad
from scipy.sparse import csr_matrix
from collections import Counter
from ast import literal_eval
import argparse
import json

mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['ps.fonttype'] = 42
mpl.rcParams['font.family'] = 'Arial'


# 572-630 are ITD region
mutations = [
'E573insE',
'S574insS',
'Q575insQ',
'L576insL',
'Q577insQ',
'M578insM',
'V579insV',
'Q580insQ',
'V581insV',
'T582insT',
'G583insG',
'S584insS',
'S585insS',
'D586insD',
'N587insN',
'E588insE',
'Y589insY',
'F590insF',
'Y591insY',
'V592insV',
'D593insD',
'F594insF',
'R595insR',
'R595insRE',
'E596insE',
'E596insEY',
'Y597insY',
'E598insE',
'Y599insY',
'D600insD',
'L601insL',
'K602insK',
'W603insW',
'E604insE',
'F605insF',
'P606insP',
'R607insR',
'E608insE',
'N609insN',
'L610insL',
'E611insE',
'F612insF',
'G613insG',
'K614insK',
'V581insVTGSSDNEYFYVDFREYEYDLKWEFPRENL',
'G583insGSSDNEYFYVDFREY',
'G583insGSSDNEYFYVDFREYE',
'G583insGSSDNEYFYVDFREYEYDLKWEFPRE',
'G583insGSSDNEYFYVDFREYEYDLKWEFPRENL',
'G583insGSSDNEYFYVDFREYEYDLKWEFPRENLE',
'S584insSSDNEYFYVDFR',
'S584insSSDNEYFYVDFRE',
'S584insSSDNEYFYVDFREY',
'S584insSSDNEYFYVDFREYEYD',
'S584insSSDNEYFYVDFREYEYDLKWEFP',
'S584insSSDNEYFYVDFREYEYDLKWEFPRE',
'S584insSSDNEYFYVDFREYEYDLKWEFPRENL',
'S585insSDNEYFYVDFR',
'S585insSDNEYFYVDFREYEYDLKWEFP',
'S585insSDNEYFYVDFREYEYDLKWEFPRE',
'D586insDNEYFYVDF',
'D586insDNEYFYVDFR',
'N586insDNEYFYVDFREYEYDLKWEFP',
'N587insNEYFYVDFREYEYDLKWE',
'N587insNEYFYVDFREYEYDLKWEFP',
'E588insEYFYVDF',
'E588insEYFYVDFR',
'E588insEYFYVDFREYEYDLKWEFP',
'Y591insYVDFREYE',
'V592insVDFREY',
'V592insVDFREYE',
'D593insDFREY',
'F594insFREY',
'F594insFREYE',
'F594insFREYEYDL',
'F594insFREYEYD',
'R595insREY',
'R595insREYEYD',
'R595insREYEYDL',
'Y597insYEYDLKW',
'E598insEYDLKWEF',
'Y599insYDLKWEFP'
]

flt3 = 'MPALARDGGQLPLLVVFSAMIFGTITNQDLPVIKCVLINHKNNDSSVGKSSSYPMVSESPEDLGCALRPQSSGTVYEAAAVEVDVSASITLQVLVDAPGNISCLWVFKHSSLNCQPHFDLQNRGVVSMVILKMTETQAGEYLLFIQSEATNYTILFTVSIRNTLLYTLRRPYFRKMENQDALVCISESVPEPIVEWVLCDSQGESCKEESPAVVKKEEKVLHELFGTDIRCCARNELGRECTRLFTIDLNQTPQTTLPQLFLKVGEPLWIRCKAVHVNHGFGLTWELENKALEEGNYFEMSTYSTNRTMIRILFAFVSSVARNDTGYYTCSSSKHPSQSALVTIVEKGFINATNSSEDYEIDQYEEFCFSVRFKAYPQIRCTWTFSRKSFPCEQKGLDNGYSISKFCNHKHQPGEYIFHAENDDAQFTKMFTLNIRRKPQVLAEASASQASCFSDGYPLPSWTWKKCSDKSPNCTEEITEGVWNRKANRKVFGQWVSSSTLNMSEAIKGFLVKCCAYNSLGTSCETILLNSPGPFPFIQDNISFYATIGVCLLFIVVLTLLICHKYKKQFRYESQLQMVQVTGSSDNEYFYVDFREYEYDLKWEFPRENLEFGKVLGSGAFGKVMNATAYGISKTGVSIQVAVKMLKEKADSSEREALMSELKMMTQLGSHENIVNLLGACTLSGPIYLIFEYCCYGDLLNYLRSKREKFHRTWTEIFKEHNFSFYPTFQSHPNSSMPGSREVQIHPDSDQISGLHGNSFHSEDEIEYENQKRLEEEEDLNVLTFEDLLCFAYQVAKGMEFLEFKSCVHRDLAARNVLVTHGKVVKICDFGLARDIMSDSNYVVRGNARLPVKWMAPESLFEGIYTIKSDVWSYGILLWEIFSLGVNPYPGIPVDANFYKLIQNGFKMDQPFYATEEIYIIMQSCWAFDSRKRPSFPNLTSFLGCQLADAEEAMYQNVDGRVSECPHTYQNRRPFSREMDLGLLSPQAQVEDS'

with open('/gpfs/data/yarmarkovichlab/Frank/pan_cancer/atlas/AML/db_fasta/FLT3_ITD_mutation.fasta','w') as f:
    for mut in mutations:
        before,after = mut.split('ins')
        pos = int(before[1:])
        before = before[0]
        assembled = flt3[:pos-1] + after + before + flt3[pos:]
        f.write('>FLT3|{}|na|na|ENSG00000122025|na|na|inframe_insertion\n{}\n'.format(mut,assembled))


